//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremierHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int HomeTeamId { get; set; }
        public int AwayTeamId { get; set; }
        public int StadiumId { get; set; }
        public string LiveScoreLink { get; set; }
        public string HomeTeamGoals { get; set; }
        public string AwayTeamGoals { get; set; }
        public string Highlights { get; set; }
    
        public virtual AwayTeam AwayTeam { get; set; }
        public virtual HomeTeam HomeTeam { get; set; }
        public virtual Stadium Stadium { get; set; }
    }
}
